---
title: "03_Projektbericht"
author: "Andrin Dobler, Joel Jonischus"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_depth: 3 # up to three levels
    toc_float: true # table of contents on left
    number_sections: true # number sections
fontsize: 11pt
geometry: margin=2.5cm
---

**Kurs:** Quantitative Research Methods, HS25  
**Team / Autor:innen:** Andrin Dobler, Joel Jonischus  
**Projekt:** Unternehmerisch geprägt? Familiäre Einflüsse auf Gründungsabsichten nach dem Studium  
**Repository** <https://github.com/andrindobler/Projektarbeit_Quant_fhgr>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)

#libraries
library(openxlsx)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(plotly)

#Access to data set
guess <- read.xlsx("GUESSS.xlsx", sheet = 1)

#Data sources
source("scripts/stat_kennwerte.R")
source("scripts/graphs.R")

```

# 1 Einleitung und Fragestellung

Ob Studierende eine unternehmerische Laufbahn in Betracht ziehen, hängt nicht allein von individuellen Interessen oder Bildungsangeboten ab, sondern wird auch durch ihr soziales Umfeld geprägt. Insbesondere das familiäre Umfeld kann früh unternehmerische Denkweisen, Rollenbilder und Risikoeinstellungen vermitteln. Die GUESSS-Studie „Studentisches Unternehmertum in der Schweiz 2018“ bietet eine fundierte empirische Grundlage, um diesen Zusammenhang näher zu beleuchten. Im folgenden Abschnitt wird daher der Frage nachgegangen, ob Studierende mit unternehmerischem Familienhintergrund höhere Gründungsabsichten aufweisen als ihre Kommilitoninnen und Kommilitonen ohne einen solchen Hintergrund.
  
# 2 Wie beeinflusst die von Studierenden erwartete Unterstützung oder Zurückhaltung seitens ihrer Familie ihre Absicht, ein Unternehmen zu gründen?

Der Mittelwert der familiären Reaktion liegt bei**`r round(mean_Q6.2_1, 2)`** (SD = `r round(sd_Q6.2_1, 2)`).




